# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0019_auto_20160222_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='o_ring_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'O-ring info'),
        ),
    ]
